// Canonical key order for a normalized package.json, applied by sort_package_json_keys.
// Mirrors the conventional npm field ordering; keys absent from a manifest are skipped and
// unknown keys are appended in their original order.
const PACKAGE_JSON_KEY_ORDER: ReadonlyArray<string> = [
	'name',
	'version',
	'description',
	'keywords',
	'homepage',
	'bugs',
	'license',
	'author',
	'contributors',
	'funding',
	'files',
	'main',
	'browser',
	'exports',
	'imports',
	'bin',
	'man',
	'directories',
	'repository',
	'type',
	'types',
	'typings',
	'typesVersions',
	'publishConfig',
	'private',
	'scripts',
	'config',
	'dependencies',
	'devDependencies',
	'peerDependencies',
	'peerDependenciesMeta',
	'bundleDependencies',
	'bundledDependencies',
	'optionalDependencies',
	'overrides',
	'resolutions',
	'packageManager',
	'engines',
	'devEngines',
	'os',
	'cpu',
	'size-limit',
	'pnpm',
]

export { PACKAGE_JSON_KEY_ORDER }
