// Phrases retracted from the distributed documents, kept so a clone or a reverted decision cannot
// creep back unnoticed (joshuafolkken/kit#1923). This is the small negative table that replaced the
// ~140 scattered `not.toContain` assertions the per-rule marker suites carried: each phrase is
// checked absent from the whole document corpus at once by `document-markers.test.ts`.
//
// Whitespace is collapsed on both sides before the comparison, so a phrase that the formatter would
// wrap across a line break is still caught. A phrase here must stay genuinely gone everywhere; if one
// is ever a legitimate part of a new document, remove its row rather than scoping it.
const RETIRED_PHRASES: ReadonlyArray<string> = [
	'"Implemented <title>:',
	'"dev": "vite dev --port $(josh port dev)',
	'"dev": "vite dev --port $(pnpm josh port dev)',
	'"preview": "wrangler dev --port $(josh port preview)',
	'"preview": "wrangler dev --port $(pnpm josh port preview)',
	'"preview:stop": "kill-port $(josh port preview)',
	'"preview:stop": "kill-port $(pnpm josh port preview)',
	'### セッション対話の言語（`JOSH_SESSION_LANG`）',
	'**2 つ目を作ってはならない。**',
	'**2 件目以降で `--exclude` を省略してはならない。**',
	'**EPIC 作成へ落ちてはならない。**',
	'**`#N` が宣言された順序に載っていなくても構わない。**',
	'**`--ordered` は必須であって好みの問題ではない。**',
	'**`-u` は省略できない。**',
	'**■ Overview (plain language — always first)**',
	'**書き換えられた lock ファイルは最初の子と一緒に入る。**',
	'--- 技術詳細 ---',
	'2 件以上に分割したら常に epic を作る。件数の閾値も、実行順序の有無による分岐も無い',
	'3-6 line work summary',
	'3–6 line work summary',
	'Artifact languages are unaffected',
	'Ask the user to run `pnpm josh test` and share the output',
	'CI only runs the suite it can find, so specs stay under',
	'CI status check indicates a managed config file was updated',
	"Cross-package problems → interrupt with a new Issue, don't patch locally.",
	'EPIC 全体で 1 回の質問',
	'Fix in place and re-run `/code-review` at the level `pnpm josh review:level` prints on `git diff main`',
	'Implement + PR',
	'Invoking `halfrun` authorizes commit, push, and PR creation',
	'Issue / PR / Telegram の言語は英語のまま変更なし',
	'Issue plan comments MUST be written in English',
	'Issue 本文に「`halfrun` で実行すること」と書いても強制力が無く',
	'Neither toolkit carries `shot` yet',
	'No toolkit ships that command yet',
	'Plan comments MUST be in English',
	'Poll at the polling interval; ask',
	'Post the agreed plan in English',
	'Post the plan in English',
	'Print the headings exactly as written',
	'Re-run after applying fixes until **no high or medium findings remain**.',
	'The recommended default when in doubt is the root-cause interrupt',
	'The user runs `pnpm josh test` and shares the full output',
	String.raw`Today that\n> is every consumer`,
	'Typing `halfrun` approved implementing and merging',
	'Verify **every** rule below. These are non-standard, so call out any violation.',
	'What still waits for a person, today',
	'`into owner/repo#N` は正しい書式である',
	'`queue` との違いはひとつだけである',
	'about 60 characters in Japanese, 15 words in English',
	'artifact languages (Issue / PR / Telegram = English) are unchanged',
	'ask them to run **`pnpm josh test`** locally',
	'blocker を見る前に',
	'chain-rule decision table in \\',
	'code-reviewer',
	'compose an implementation summary in English',
	'exactly what it was) → `pnpm josh git -y` →',
	'exists in neither toolkit yet',
	'fix them in place and re-run `/code-review` at the level `pnpm josh review:level` prints. Nothing is committed yet',
	'fresh-context',
	'fresh-context subagent',
	'gh issue list --label review-round2-skipped',
	'including commit, push, PR creation',
	'is a separate deliverable',
	"it asks only after a child that ran in the parent's own context",
	'its own `pnpm josh gate` join',
	'join it, and `pnpm josh git -y`; on `skip`',
	'kit exports that rule for consumers and does not apply it to itself',
	'operating-rules.md` → "Auto-merge',
	'park したことで人が必要になる',
	'park しない',
	'park は依存として表現できない場合に限る',
	'post the final review markdown as a PR comment',
	'queue #101',
	'runs the same pipeline through PR creation',
	'sleep the polling interval and go back to step 1',
	'stay in English regardless of `JOSH_SESSION_LANG`',
	'stop before merge',
	'stop with the PR OPEN',
	'the artifact language stays English',
	'the completed PR diff',
	"the threshold is the same number the epic's own measurement produced",
	'through PR creation',
	'until the user confirms E2E passed',
	'while the PR is still OPEN',
	'→ `pnpm josh git -y` → the follow-up filing',
	'→ join → `pnpm josh git -y`,',
	'■ これからやること',
	'この停止は残す',
	'これが無いと、判断が返ったのに子が永久に止まる',
	'これは advisory であり、アトミックではない',
	'これは分割ではない',
	'これは意図した差である',
	'そのたびに人が口頭で起票先を指示していた',
	'どちらを取るか迷う場合は、**根本対応（割り込み Issue）を既定とする**',
	'コミット後かつ `pnpm josh followup` 実行前',
	'マップが答えるのは「チェックアウトがどこにあるか」であって',
	'ラウンドごとのコミットや CI 再実行も発生しない',
	'ラベルはリポジトリごとに一度作る',
	'レビュー自体はコミットの前のままで',
	'今こうなっている: <1文',
	'位置の判断は対象 EPIC が既に採ってきた基準に従う',
	'候補画像からの採用決定など',
	'入口ごとに条件が違う状態は欠陥である',
	'入口だけがこの記法から取り残されていた',
	'勝手に clone することは人の作業機の配置を勝手に決めることである',
	'子 1 件の `fullrun` は分単位。これより短くしても API 消費が増えるだけ',
	'子が 13 件なら stash も 13 個になる',
	'子を実装するリポジトリではない',
	'実行手順の正典は本節であり',
	'常駐判定の問いは',
	'成果物が存在した時点で入れる',
	'成果物の良し悪しは機械では測れない',
	'成果物は常に英語',
	'打ち忘れた回の Issue はどの EPIC にも属さない',
	'排他はリポジトリ単位であり、それを適用するのは `epic:next` である',
	'推薦は信号が弱ければ何もしないが',
	'新規 EPIC を作る前に、`#N` が既に EPIC の子でないかを確かめる',
	'日本語で 60 字程度',
	'昇格が他人の Issue を容れ物へ書き換える構造変更であり',
	'最後の行が最も重要である',
	'検討した 3 案のうち',
	'片方だけでは後から辿れない',
	'理由は綴りである',
	'省略可能な確認ではない',
	'矛盾を抱えた計画に対して一括決定を行っても、決定ごと作り直しになる',
	'確認という歯止めを外す以上、上限を付ける',
	'禁じられているのは裸の',
	'自分で外せる印は印として機能せず',
	'自動投稿される Issue コメント文面は英語で記載する',
	'読み取りにこそ付け忘れやすく、付け忘れは黙って通る',
	'閉じていない blocker を宣言している候補を除外する',
]

export { RETIRED_PHRASES }
