import path from 'node:path'

const RECOVERY_COMMAND = 'josh doctor --fix'
const GLOBAL_REINSTALL_COMMAND = 'pnpm add -g @joshuafolkken/kit'
// Markers identifying a `josh` on PATH that was generated by an old kit `postinstall`
// (pre-0.200.0 `install-bin.ts` wrote a shim referencing the kit package / tsx runner).
const KIT_SHIM_MARKERS: ReadonlyArray<string> = [
	'@joshuafolkken/kit',
	'@joshuafolkken+kit',
	'install-bin',
]

type ReclaimAction = 'remove' | 'none'

interface ReclaimDecision {
	action: ReclaimAction
	target?: string
	reason: string
}

const NO_SHADOW_REASON = 'no PATH shadowing detected'
const NOT_KIT_SHIM_REASON =
	'the shadowing binary is not a kit shim — remove it manually if it is unexpected'
const RECLAIM_REASON = 'reclaimed the global josh by removing the stale kit shim'

function normalize_path(target: string): string {
	return path.resolve(target)
}

// Extract an absolute path from possibly noisy command output: `pnpm bin -g` prepends a
// `[WARN] Using --global …` line to stdout when run inside a project, so take the last line that
// looks like an absolute POSIX path. Undefined when no such line is present.
function last_path_line(stdout: string): string | undefined {
	const candidates = stdout
		.split('\n')
		.map((line) => line.trim())
		.filter((line) => line.startsWith(path.sep))

	return candidates.at(-1)
}

// PATH shadowing: the `josh` first on PATH is not the pnpm-global install. Both paths must be known
// for a comparison — an undefined side means we cannot prove shadowing, so report false.
function is_shadowed(path_josh: string | undefined, global_josh: string | undefined): boolean {
	if (path_josh === undefined || global_josh === undefined) return false

	return normalize_path(path_josh) !== normalize_path(global_josh)
}

// A reclaimable kit shim references the kit package or the removed install-bin script in its body.
function is_kit_shim(content: string): boolean {
	return KIT_SHIM_MARKERS.some((marker) => content.includes(marker))
}

// Decide whether `doctor --fix` may safely remove the shadowing binary. Only a confirmed kit shim
// is removed; any other shadowing binary is left untouched and reported for manual review.
function decide_reclaim(
	path_josh: string | undefined,
	global_josh: string | undefined,
	shim_content: string,
): ReclaimDecision {
	if (!is_shadowed(path_josh, global_josh)) return { action: 'none', reason: NO_SHADOW_REASON }
	// is_shadowed already guarantees path_josh is defined; this narrows the type for the return.
	if (path_josh === undefined) return { action: 'none', reason: NO_SHADOW_REASON }
	if (!is_kit_shim(shim_content)) return { action: 'none', reason: NOT_KIT_SHIM_REASON }

	return { action: 'remove', target: path_josh, reason: RECLAIM_REASON }
}

function format_shadow_warning(path_josh: string, global_josh: string): string {
	return [
		"⚠ PATH shadowing: the 'josh' first on PATH is not the pnpm-global install.",
		`  On PATH:     ${path_josh}`,
		`  pnpm global: ${global_josh}`,
		`  Recover:     ${RECOVERY_COMMAND}`,
	].join('\n')
}

const doctor_logic = {
	RECOVERY_COMMAND,
	GLOBAL_REINSTALL_COMMAND,
	NO_SHADOW_REASON,
	NOT_KIT_SHIM_REASON,
	RECLAIM_REASON,
	normalize_path,
	last_path_line,
	is_shadowed,
	is_kit_shim,
	decide_reclaim,
	format_shadow_warning,
}

export type { ReclaimAction, ReclaimDecision }
export { doctor_logic }
